### ISSUE TITLE
DOC: Nome do arquivo errado na 'Instalação do Quartus Help'

### ISSUE THREAD

**Issue by vitumenezes** [arthurmteodoro/install-quartus-linux#1]
No capítulo **Instalação do Quartus Help** o nome do arquivo `$ ./QuartusLiteSetup-18.0.0.614-linux.run` está errado.

O certo seria `$ ./QuartusHelpSetup-18.x-linux.run` (ao menos na atual versão 18.01)

Detalhe besta, mas já ajuda :D

**Comment by vitumenezes** [comment]
#2

**Comment by arthurmteodoro** [comment]
Problema já foi resolvido com o merge do PR #2.
